### ISSUE TITLE
RPI 1576: zVSAM Point KGE for a non-existing key value returns last record preceding the requested key

### ISSUE THREAD

**Issue by adelosa** [z390development/z390#153]
Raised by John Hennesy 2016/03/10
zVSAM Point KGE for a non-existing key value will return last record preceding the requested key, rather than the record following the requested key. More details in mail from John Hennesy dd 2016-03-10 12:16

**Comment by z390org** [comment]
Email by John Hennesy:

Abe,
 
I've included the relevant part pf the binary search from vz390.java below
 
As you will see the "next_key_rec" is calculated as " = (high_key_rec + low_key_rec + 1) / 2".
 
Let us suppose that the KSDS has 7 keys:- AZ, BZ, CZ, DZ, EZ, FZ, GZ.
Which are referred to as records 0 thru 6.
 
high_key_rec = sz390.tiot_eof_rba[cur_vx0_tiot_index] / vx0_lrec;
low_key_rec = 0;
 
Thus the first time thru the "while", high_key_rec is equal to the XRBA of the EOF of the VX0 divided by the vx0_lrec,
which comes out as 7.
 
Thus the calculation of the next_key_rec the first time thru is (0 + 7 + 1) / 2 = 4.
 
Now suppose we are looking for AZ, then our calculations will be
 
(0 + 4  + 1) / 2 = 2
 
(0 + 2 + 1) / 2 = 1
 
(0 + 1 + 1) / 2 = 1
 
We can't reach record 0, so the inclusion of code
 
    if (next_key_rec == last_key_rec && next_key_rec > 0) {
     next_key_rec--;
    }
which in the above case should change the value of next_key_rec from 1 to 0.
And indeed it does.
 
But it also reduces the value in other places where it shouldn't.
As below where I'm trying to run a KGE for DA
 
22:03:08 JKPKGEDA  jez390 START USING z390 V1.5.06 ON J2SE 1.8.0 03/09/16
JKPKGEDA QUERY POINT AT DA
find_ksds_key 2 next_key_rec=4!!!!!!!!
comp_key 10 # comp_rc=-1
find_ksds_key 13 # low_key_rec======0!!!!!!!!
find_ksds_key 14 # high_key_rec=====4!!!!!!!!
find_ksds_key 16 next_key_rec=====2!!!!!!!!
find_ksds_key 16 last_key_rec=====4!!!!!!!!
comp_key 10 # comp_rc=1
find_ksds_key 13 # low_key_rec======2!!!!!!!!
find_ksds_key 14 # high_key_rec=====4!!!!!!!!
find_ksds_key 16 next_key_rec=====3!!!!!!!!
find_ksds_key 16 last_key_rec=====2!!!!!!!!
comp_key 10 # comp_rc=-1
find_ksds_key 13 # low_key_rec======2!!!!!!!!
find_ksds_key 14 # high_key_rec=====3!!!!!!!!
find_ksds_key 16 next_key_rec=====3!!!!!!!!
find_ksds_key 16 last_key_rec=====3!!!!!!!!
find_ksds_key 17 next_key_rec=====2!!!!!!!!
find_ksds_key 21 # kge - comp_rc=-1
JKPKGEDA ENDED OK
22:03:08 JKPKGEDA  jez390 ENDED   RC= 0 SEC= 0 MEM(MB)= 11 IO=48 INS=30
It should find DZ at next_key_rec of 3, but because of the corrective code above it reduces it to 2.
 
 
 
 private boolean find_ksds_key() {
  /*
   * search vx0 for ksds key in rplarg and set cur_vx0_xrba entry if found
   * else false.
   */
  tot_vxn_find++;
  vx0_lrec = 8 + cur_vclr_klen;
  high_key_rec = sz390.tiot_eof_rba[cur_vx0_tiot_index] / vx0_lrec;
  low_key_rec = 0;
  next_key_rec = (high_key_rec + low_key_rec + 1) / 2;
  if (next_key_rec == high_key_rec){
   next_key_rec = 0; // RPI 1016
  }
  last_key_rec = -1;
  prev_key_rec = -1;
  if (tz390.opt_tracev) {
   tz390.put_trace("VSAM FIND KEY=" + tz390.get_hex(cur_rpl_arg, 8)
     + " LEN=" + tz390.get_hex(comp_key_len, 8));
   sz390.dump_mem(pz390.mem, cur_rpl_arg, comp_key_len);
  }
  byte cur_node_depth = 0;
  while (next_key_rec != last_key_rec && next_key_rec != prev_key_rec) {
   cur_node_depth++;
   if (cur_node_depth > max_vxn_height){
    max_vxn_height = cur_node_depth;
   }
   cur_vx0_xrba = next_key_rec * vx0_lrec;
   if (read_ksds_index()) {
    prev_key_rec = last_key_rec;
    prev_key_vx0_xrba = last_key_vx0_xrba;
    prev_key_ves_xrba = last_key_ves_xrba;
    prev_key_gen_rc = last_key_gen_rc;
    last_key_rec = next_key_rec;
    last_key_vx0_xrba = cur_vx0_xrba;
    last_key_ves_xrba = cur_ves_xrba;
    comp_key(cur_rpl_arg, cur_key);
    last_key_gen_rc = comp_key_gen_rc;
    if (comp_rc == 0) {
     if (cur_ves_xrba < 0) {
      if (find_ksir()) {
       cur_ves_xrba = cur_ksir_rec;
       set_rpl_cur_rec(true);
       return true;
      } else {
       return false;
      }
     }
     set_rpl_cur_rec(true);
     return true;
    }
    if (comp_rc > 0) {
     low_key_rec = next_key_rec;
    } else {
     high_key_rec = next_key_rec;
    }
    next_key_rec = (high_key_rec + low_key_rec + 1) / 2;
    if (next_key_rec == last_key_rec && next_key_rec > 0) {
     next_key_rec--;
    }
   } else {
    return false;
   }
  }

**Comment by z390org** [comment]
This issue is to be addressed in zVSAM V2. If anyone encounters this issue in zVSAM V1 without having a work-around, please reopen the issue.
