### ISSUE TITLE
RPI 1635: Jar file to include Manifest file

### ISSUE THREAD

**Issue by adelosa** [z390development/z390#206]
Raised by Hugh Sweeney 2019/03/02
Make sure Manifest file is included when creating a jar file. See mail by Hugh Sweeney dd 2019-03-02 12:58

**Comment by z390org** [comment]
Email by Hugh Sweeney:


Yo guys,

On Tue, 26 Feb 2019 at 20:28, Abe Kornelis <abe@bixoft.nl> wrote:

    Hugh,

>>             Melvyn had problems starting the GUI, that I fixed. I don't believe there is any problem starting the GUI now that was introduced later than 1.5.06.
>>
>         **--> Introduction date is not too relevant. If the problem is reproducible on beta 12 or later, I will create an RPI.
>
>     We have different perspectives. If the problem is reproducible on beta 12 or earlier, there's no point my looking for it in my code. I wouldn't like any problem to slip down the cracks between these two perspectives :)

    **--> I agree that it would be pointless for you to try and fix
              a pre-existing issue while trying to keep focussed on zVSAM V2.

HS: and probably pointless even if I had no zVSAM v2 work on my plate. I have knowledge of only a very narrow slice of the existing Java code. (And product.)

 

              Also, I've come to realize that the way the jar file is created may
              influence its behaviour. Which means that there might be issues
              that do not show in Don's V1.5.06 jar, but would show if I created
              a new jar from those same source files.

              It's something to be aware of...

HS: just adding for completeness: the two potential faults that I'm aware of are

    creating the JAR from within the wrong directory, rather than the one containing the class files. The JAR is created successfully, but contains path information relative to the current directory at the time of creation. Those will be wrong at runtime.
    Omitting the Manifest file. This does not matter if running the emulator from a script such as EXEC.BAT myPgm.390, but is needed if you want to execute the JAR file directly. In that case, the Manifest tells Java to bring up the interactive GUI.


              I understand you deem the issue unworthy of an RPI.
              Which is fine - provided the issue does not exist in beta 12 or earlier.
              Because if it does, I'll have to repeat your repair actions!

HS: I don't recall deeming it unworthy of an RPI. On the contrary, my feeling is that bringing up the interactive GUI ought to be part of pre-deployment testing. Because all the z/OS functionality could run cleanly from the command line, but double-clicking the z390 icon would crash if the Manifest file is missing.

Hugh
--

**Comment by adelosa** [comment]
My view is this has been addressed through the automated build PR that has now been merged. 
Fixed by #313 and #333.
