### ISSUE TITLE
RPI 1647: SOC1 error on BRCTH instruction

### ISSUE THREAD

**Issue by adelosa** [z390development/z390#217]
Raised by Melvyn Maltz 2021/03/15
BRCTH instruction assembles but causes S0C1 when executed. See mail by Melvyn Maltz dd 2021-03-15 12:37

**Comment by z390org** [comment]
TRS file produced by Melvyn Maltz:

TRS= ZPARTRS Z390 PROGRAM ANALYSIS REPORT TRACE SOURCE V1.5.01b 10/28/09
TRS= SYSPARM=E:\Z390\PROGRAMS\SAMPLE3+DETAIL+ALL
TRS= PARM(1)=E:\Z390\PROGRAMS\SAMPLE3
TRS= PARM(2)=DETAIL
TRS= PARM(3)=ALL
TRS= CURRENT DATE=03/10/21 TIME=12.21
12:20:59 MSG=SAMPLE3   EZ390 START USING z390 V1.5.06 ON J2SE 1.7.0_67 03/10/21
12:20:59 MSG=TRACE MEMORY FQE      LOC=00008000 LEN=000F8000 NXT=00000000
12:20:59 MSG=TRACE MEMORY GETMAIN  LOC=000FFF70 LEN=00000090 NXT=00000000
12:20:59 MSG=TRACE MEMORY FQE UPDT LOC=00008000 LEN=000F7F70 NXT=00000000
12:20:59 MSG= CDE LOAD=800FFF70 LEN=00000090 NAME=E:\Z390\PROGRAMS\SAMPLE3.390
12:20:59 TRS= SCANNING  E:\Z390\PROGRAMS\SAMPLE3.LST LOAD=00FFF70
12:20:59 TRS= INCLUDING E:\Z390\PROGRAMS\SAMPLE3.PRN LOAD=00FFF70
12:20:59 TRS= LOADED SOURCE FROM PRN CBL=0 ECC=0 ASM=12 ECA=0
12:20:59 MSG=TRACE MEMORY FQE      LOC=00008000 LEN=000F7F70 NXT=00000000
12:20:59 MSG=TRACE MEMORY GETMAIN  LOC=000FFF48 LEN=00000028 NXT=00000000
12:20:59 MSG=TRACE MEMORY FQE UPDT LOC=00008000 LEN=000F7F48 NXT=00000000

12:20:59  800FFF70 0 90ECD00C      STM   RE=00002018 RC=F4F4F4F4 S2(0000210C)=00000000
12:20:59  SAMPLE3  000000 SAMPLE3  STM   14,12,12(13)
12:20:59  800FFF74 0 45FF0068      BAL   RF=800FFF70 S2(000FFFD8)=50FD0008 ST
12:20:59  SAMPLE3  000004          BAL   15,104(15)

12:20:59  800FFFD8 0 50FD0008      ST    RF=800FFF78 S2(00002108)=00000000
12:20:59  SAMPLE3  000068          ST    15,8(13)
12:20:59  800FFFDC 0 50DF0004      ST    RD=00002100 S2(000FFF7C)=00000000
12:20:59  SAMPLE3  00006C          ST    13,4(15)
12:20:59  800FFFE0 0 18DF          LR    RD=00002100 RF=800FFF78
12:20:59  SAMPLE3  000070          LR    13,15
12:20:59  800FFFE2 0 C0A800000005  IIHF  RA=F4F4F4F4F4F4F4F4 I2=00000005
12:20:59  SAMPLE3  000072          IIHF  R10,5
12:20:59  800FFFE8 0 CCA600000000  BRCTH RA=F4F4F4F4 S2(000FFFE8)=CCA600000000 BRCTH
12:20:59  SAMPLE3  000078 LOOP     BRCTH R10,LOOP

12:20:59 MSG=EZ390E error  11 ABEND PSW=07050600 800FFFEA 0000         ????? ABEND S0C1
12:20:59 MSG= R0-R3 F4F4F4F4800FFF70 F4F4F4F400002300 F4F4F4F4F4F4F4F4 F4F4F4F4F4F4F4F4
12:20:59 MSG= R4-R7 F4F4F4F4F4F4F4F4 F4F4F4F4F4F4F4F4 F4F4F4F4F4F4F4F4 F4F4F4F4F4F4F4F4
12:20:59 MSG= R8-RB F4F4F4F4F4F4F4F4 F4F4F4F4F4F4F4F4 00000004F4F4F4F4 F4F4F4F4F4F4F4F4
12:20:59 MSG= RC-RF F4F4F4F4F4F4F4F4 F4F4F4F4800FFF78 F4F4F4F400002018 F4F4F4F4800FFF78
12:20:59 MSG=EZ390E error  12 program aborting due to abend S0C1
12:20:59 MSG=SAMPLE3   EZ390 ENDED   RC=16 SEC= 0 MEM(MB)= 19 IO=24 INS=8
TRS= INPUT   FILES   LST=1 PRN INC=1 PRN EXC=0
TRS= INPUT   RECORDS TRE=26 LST=9 PRN=80
TRS= LOADED  SOURCE  CBL=0 ECC=0 ASM=12 ECA=0
TRS= SKIPPED RECORDS ASM=0 MSG=0
TRS= OUTPUT  RECORDS CBL=0 ECC=0 ASM=7 ECA=0
TRS= OUTPUT  RECORDS ERR=0 MSG=18 TRS=47
TRS= TOTAL MNOTE ERRORS=0  MAX RETURN CODE=0

**Comment by dsh33782** [comment]
Fixed in pz390.java in z390_v1706
