### ISSUE TITLE
Replace obsolete Copyrights  

### ISSUE THREAD

**Issue by dsh33782** [z390development/z390#236]
Replace obsolete copyrights for Automated Software Tools Corp. which no longer exists, and replace them with copyright by Don Higgins with current year.  There may be other copyrigth and GPL license changes required.

**Comment by adelosa** [comment]
Some interesting reading here regarding topic of copyright attribution: https://haacked.com/archive/2006/01/26/WhoOwnstheCopyrightforAnOpenSourceProject.aspx/ 

On this basis, do we need to get contributors to agree to assigning copyright to Don as part of contributing to the project, otherwise the copyright remains with them.

I know that Don has been replacing copyright messages - does that mean he is working on this item, or are we looking for someone to do this.. If you are, I'd be happy to take this on and leave you folk to the heavy lifting stuff. 

Also should this be merged with #113 as this is talking about GPL license. Probably makes sense to combine.

**Comment by abekornelis** [comment]
@dsh33782 Would please read the article mentioned by Anthony? It might help decide how to continue with copyright ownership.

**Comment by dsh33782** [comment]
Anthony has offered to change all the copyrights.  I have proposed the following changes to all copyrights by Don Higgins and by Automated Software Tools Corporation which I closed in 2012:

Copyright 2019 z390 Assembler LLC
Open source software under General Public License v2

The z390 Assembler LLC has been filed with the State of Florida and should be completed by December 20, 2021 in time for Beta1 release v1.8.00.
