### ISSUE TITLE
Update cics bat commands to reflect new cics subdirectories

### ISSUE THREAD

**Issue by dsh33782** [z390development/z390#245]
The cics directory now has the following new subdirectories: 390, bat, cbl, cpy, mac, and mlc.
The bat commands need to be updated to use these subdirectories.

**Comment by abekornelis** [comment]
@jyganci is this something you would like to do? with Melvyn if needed...

**Comment by adelosa** [comment]
@abekornelis @jyganci I accidently started doing this. Came here because I am trying to write a "HELLO zCICS" tutorial and having no luck getting zCICS it working. 

Decided to work through the recompile process and noticed the broken BAT files and new folder structure. 
Tried assembling the first module (GBL0602) and it is failing. 
I came here to log an issue.. 

```text
19:26:59 GBL0602   MZ390 START USING z390 V1.7.07 ON J2SE 14.0.2 06/30/21
MZ390E MNOTE 12,'GENCB ACB EXLST NOT CURRENTLY SUPPORTED'
MZ390E MNOTE 12,'GENCB ACB EXLST NOT CURRENTLY SUPPORTED'
MZ390E MNOTE 12,'GENCB ACB EXLST NOT CURRENTLY SUPPORTED'
MZ390E MNOTE 12,'GENCB ACB EXLST NOT CURRENTLY SUPPORTED'
MZ390E error 217      (11/63)63 invalid substring - offset=4 len=-3
MZ390E error 217      (11/63)63 invalid substring - offset=4 len=-3
MZ390E error 217      (11/63)63 invalid substring - offset=4 len=-3
MZ390E error 217      (11/63)63 invalid substring - offset=4 len=-3
MZ390E error 217      (11/63)63 invalid substring - offset=4 len=-3
MZ390E error 217      (11/63)63 invalid substring - offset=4 len=-3
AZ390E error  98       (1/65)83            USING IHAVCLR,R10
AZ390E error 198     (1/107)137            MVC   RPLLKEY,VCLRKLEN   DEFAULT TO CATALOG BASE KEYLENGTH
AZ390E error  98     (1/111)141            USING IHAVAIX,R12
AZ390E error 198     (1/112)142            MVC   RPLLKEY,VAIXKLEN   DEFAULT TO CATALOG AIX KEYLENGTH
AZ390E error 198     (1/122)152            CLC   FCPKEYLN,VAIXKLEN+2 VALIDATE AIX GENERIC KEYLENGTH ?
AZ390E error 207     (1/124)154            DROP  R12
AZ390E error 198     (1/128)158            CLC   FCPKEYLN,VCLRKLEN+2 VALIDATE BASE GENERIC KEYLENGTH ?
AZ390E error 198     (1/160)194            L     R5,VCLRLREC        R5=LENGTH
AZ390E error 198     (1/161)195            TM    VCLRFLG1,VCLRVREC  IS IT VARIABLE ?
AZ390E error 198     (1/176)230            TM    VCLRFLG1,VCLRVREC  IS IT VARIABLE ?
AZ390E error 198     (1/182)236            MVC   FCPACLEN-DFHFCBLK(4,R5),VCLRLREC SAVE FIXED LRECL
AZ390E error 207     (1/183)237            DROP  R10
AZ390E error  29     (1/483)853            VCDTD ,                  VSAM CLUSTER DEFINITION TABLE
AZ390E ERRSUM Critical Error Summary Option
AZ390E ERRSUM Fix and repeat until all nested errors resolved
AZ390E ERRSUM missing macro =VCDTD
AZ390E ERRSUM total missing   copy   files =0
AZ390E ERRSUM total missing   macro  files =1
AZ390E ERRSUM total undefined symbols      =6
AZ390E ERRSUM total mz390 errors    = 6
AZ390E ERRSUM total az390 errors    = 13
19:27:00 GBL0602   MZ390 ENDED   RC=12 SEC= 0 MEM(MB)= 58 IO=7653
```
* The missing VCDTD macro is indeed missing - looks like something changed by zVSAM.. 
* The other errors, I have not looked too deeply at.. and probably beyond my knowledge..

So is it safe at this point to say that zCICS may indeed be BROKEN at the moment..
If so, this card is probably not a great description - better off calling it "Get zCICS working with latest code base"

Happy to assist as I am keen to get zCICS running so I can write this tutorial.. but I may need assistance..
@jyganci @abekornelis -- will we need Melvyn to assist with this!

**Comment by jyganci** [comment]
I know nothing about how zCICS is put together.

The 'GENCB ACB EXLST NOT CURRENTLY SUPPORTED' error is a bug in GENCB.MAC
and/or GENCB1.MAC that I reported some time ago. Melvyn already fixed it
some time ago but apparently he did not officially submit the fix to Don.
Neither the z390_v1707.zip file nor the github repository has the fix. If I
recall correctly, GENCB.MAC was modified to not allow null values in
operands passed on to GENCB1.MAC. It is my opinion that Melvyn needs to
take care of this.

The "invalid substring - offset=4 len=-3" errors are due to a but in how
some MODCB/MODCB1/ZMODCB code is generated. The bug MAY be in mz390.java,
but at the present time the cause of the error is unknown.

The missing VCDTD.MAC file is also something Melvyn should fix.

All of these errors are VSAM-related errors, not CICS-related errors.

Regards,

John Ganci

**Comment by abekornelis** [comment]
All,

to my knowledge Melvyn has indeed fixed the errors.
I was planning to ask him for a copy to import the changes
into the repo *after* completing the pull request with the
changes that Dave Kienow supplied.

Kind regards,

Abe
===



Op 30/06/2021 om 18:37 schreef John Ganci:

**Comment by dsh33782** [comment]
Alpha2 now supports successful assembly/compile of all cics test transactions in cics\bat\DFHALL.BAT, and cics can be started and executed successfully.

**Comment by jyganci** [comment]
Don, Anthony, all,

I'm working on a new bash script, dfhall, that will be the bash version of
the cics\bat\DFHALL.BAT. My methodology is to translate DFHALL.BAT, trying
to follow line-by-line. So far I've done the "subprograms", "tables",
"maps", and "asm programs".

Looking at the first COBOL program I see a problem. Line 2 of the
DFHALL.BAT file defines the environment variable ZC39PATH as
"ZC39PATH=zcobol\z390". We've already discussed this, but there is no
longer a z390 subdirectory of zcobol. The first COBOL program compiled and
linked begins on line 1142 of DFHALL.BAT (the 3 lines shown here making up
the CBLCL call are all on one line):

SET PROGRAM=TESTBEC2
CALL bat\CBLCL %CICSPATH%\%PROGRAM% CICS
SYSMAC(%CICSPATH%+ZCOBOL\MAC+%ZC39PATH%+CICS+MAC)
SYSCPY(%CICSPATH%+ZCOBOL\CPY+%ZC39PATH%+MAC+.)

Note the use of %ZC39PATH% in the SYSMAC and SYSCPY parameters. To me, this
seems like an invalid value. However, Don says he successfully ran
DFHALL.BAT, which implies to me that the %ZC39PATH% is not needed.

Am I missing something?

Regards,

John Ganci
...

**Comment by jyganci** [comment]
Don, Anthony, all,

Okay, I did a test that seems to work. I now have the complete dfhall bash
script running successfully. I don't know how to start CICS, and then I
don't know how to test.

Here's what I did for the COBOL programs.

1. Set the 3 variables at the top of the script as follows:

cicspath=cics
zc39path=zcobol    # was zcobol/z390
progpath=linklib

2. Because parentheses have special meaning for bash, the SYSMAC and SYSCPY
parameters are set in variables, then used on the invocation of cblcl.

sysmac='sysmac('${cicspath}'+'$zc39path'/mac+mac)'
syscpy='syscpy('${cicspath}'+'$zc39path'/cpy+'$zc39path'/mac+mac+.)'

3. Change the cblcl line as follows:

program=TESTBEC1
bash/cblcl ${cicspath}/${program} CICS $sysmac $syscpy

Did 3 for all the remaining programs. All compiled and linked without error.

For DFHALL.BAT, you could do something similar.

1. Set the 3 variables at the top of the bat file.

SET CICSPATH=cics
SET ZC39PATH=zcobol\z390
SET PROGPATH=linklib

2. Not needed for bat files.

3. Modify the SYSMAC and SYSCPY parameters on the CBLCL line.

SET PROGRAM=TESTBEC1
CALL bat\CBLCL %CICSPATH%\%PROGRAM% CICS
SYSMAC(%CICSPATH%+%ZC39PATH%\MAC+MAC)
SYSCPY(%CICSPATH%+%ZC39PATH%\CPY+MAC+.)

I think this should work. If one of you is willing, please test it. Thanks.

Note: I removed a "CICS" near the right end of the SYSMAC value since the
%CICSPATH% value is "cics" and appears first in the concatenation. I think
the final "+." in the SYSCPY value (both bat and bash versions) is
redundant snce the test programs are in the cics subdirectory and it is
first in SYSCPY concatenation.

While not needed for Windows, the directory names should all be lower case
throughout DFHALL.BAT.

Regards,

John Ganci
