### ISSUE TITLE
User Issue - Windows path error 

### ISSUE THREAD

**Issue by CPSstudent** [z390development/z390#466]
I'm currently taking a computer science class that has us using z390. Every time I try to run a program I get a "'C:\PROGRA~2\Automated' is not recognized as an internal or external command,
operable program or batch file." error, how do I fix this?

**Comment by adelosa** [comment]
Hi again,
Thanks for raising your issue here. Based on the fact that the pathname includes _Automated_ I think you are working on an old version of the software.

Before we begin, can you please follow the current instructions for installation and install the most recent version of the software. I will be unable to help you if you are using an old version.

Installation instructions: https://z390development.github.io/z390/getting_started/install/

Once you follow these instructions, complete the quickstart to confirm everything is working

Quickstarts: https://z390development.github.io/z390/getting_started/quickstart/

If you have any issues with the above, let me know by providing further comments here.

If your teacher has provided instructions that use old versions, can you please point him at the above links and docs for use going forward for his students. 

Out of interest, are you able to let me know what course/subject/school is using Z390. We are excited that people are using the software and would love to promote its use.

**Comment by CPSstudent** [comment]
I reinstalled the most recent version and am now getting "The system cannot find the path specified." which I'm sure is me not doing something correctly. I am taking Computer Architecture and organization (CIS 227) at Dutchess Community College

**Comment by adelosa** [comment]
Can you copy a full log here so I can see the actual issue. I'll ask for more details depending on what i see. 
Also what version of windows are you using?

**Comment by CPSstudent** [comment]
After some additionally time and effort I figured it out and am no longer having any issues, thank you for the help!

**Comment by adelosa** [comment]
Good to hear. Good luck in your course.
