### ISSUE TITLE
initial git problem

### ISSUE THREAD

**Issue by chookperson** [z390development/z390#467]
I have downloaded git from the website suggested by Abe and installed it via the git wizard.

When I go into the command prompt, Abe says "on your local machine , create the parent directory for your clone".

My repo is called chookperson/z390 and originally I called the clone "clone" but on the install it said something about "master".

At the command prompt, I created directories for c:\clone, c:\master and c:\chookperson and in each tried git status and from each received a negative response of  "fatal: not a git repository (or any of the parent directories): .git".

I tried to enter: git clone <ctrl-V> clone
but it gave back the "help screen" for git clone when I hit the <ctrl-V>.

What parent directory is it expecting?

I successfully "forked" up to the point above but I'm stumped as how to proceed.

**Comment by adelosa** [comment]
Hi there @chookperson,
I'd be happy to assist. It sounds like you are pretty new to Git and it is a big area to learn.

If you just want some instructions for getting started with developing z390, then the 
following page provides some instructions which you should be able to adapt for your needs.

https://z390development.github.io/z390/contributing/contribute_code/

It shows the command to clone the repository - you should clone your fork (chookperson/z390) 
rather than the main repo (z390development/z390) as this is what you will need to 
submit changes.

I would also suggest that you get a basic understanding of working with Git, otherwise you are going to get very frustrated working on the project. 

There are many good Git tutorials online, but you can't go past the free book
* https://git-scm.com/book/en/v2

You don't need to be an expert, but you will need a basic understanding of how it works, especially the 
concept of a __distributed__ source control system which is very different from the centralised ones you
may be familiar with and can be confusing for new folk.

If none of that suits, then I would be happy to get on a call with you and walk you through the process so you
can see it in action.

**Comment by chookperson** [comment]
my question reveals my novice-ity with git. i have read the free book. but my question still remains unanswered. i cannot proceed without some basic help.

**Comment by adelosa** [comment]
We can organise a call and we can work through it together. 
You must be in the folder that git creates as part of the clone process for git status to work. So after clone cd into directory. 
If git status is saying it is not a git repo then it means the clone did not work. Every git repo has a '.git' folder where the repo history is stored. You may want to check for this folder.
Send me an email if you want to have a session.

**Comment by adelosa** [comment]
Closing this as conversations are continuing on new issues.
